name: flutter_jsbridge_builder
version: 2.0.3-dev
author: Dart Team <misc@dartlang.org>
description: Generates utilities to aid in serializing to/from JSON.
homepage: https://github.com/dart-lang/json_serializable
environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  analyzer: ^2.7.0
  build: ^2.1.1
  build_config: ^1.0.0


  # Use a tight version constraint to ensure that a constraint on
  # `json_annotation` properly constrains all features it provides.
  json_annotation: ^4.4.0
  meta: ^1.7.0
  path: ^1.8.0
  source_gen: ^1.1.1
  yd_bridge:
    path: ../yd_bridge

dev_dependencies:
  build_runner: ^2.1.8
  build_test: ^2.1.4
  build_verify: ^2.0.0
  build_web_compilers: ^3.2.1
  collection: ^1.15.0
  dart_style: ^2.0.0
  logging: ^1.0.0
  test: any
  yaml: ^3.1.0